#!/usr/bin/env python
# coding: utf-8
import re
import sys
import os

# sys.path.insert(0, os.path.abspath('./lib/'))
# sys.path.append(os.path.abspath('./lib/bicorn/'))
# print sys.path

from thriftzoo.app import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
